Implementation of the Orientation Filter
catsystems/cats-embedded pull request #35
Opened 2021-08-31 09:51 UTC by jbinz

This patch implements the orientation Filter. The Filter is working, however there are still some irregularities which I think are due to the magnetometer not being calibrated.

The new filter improves the orientation Kalman Filter in every aspect:
State estimation task processor usage with KF: 6.5%		free memory: 100 words
State estimation task processor usage with new filter: 4%	free memory: 600 words
Additionally the new filter takes into account that the acceleration might be very large, rendering the accel measurement useless.
It also seems to be much more stable.
Needs to be verified on a drone and on a rocket.
Closes #21

2021-08-31 13:08 UTC, stojadin2701 commented on boards/cats_rev1Pro/Core/Inc/control/orientation_filter.h
> +typedef struct {
I would put ifdefs around both of these struct definitions

2021-08-31 13:08 UTC, stojadin2701 commented on boards/cats_rev1Pro/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.19)
revert this to 3.16, I had some problems installing newer versions on my PC :)

2021-08-31 13:10 UTC, stojadin2701 commented on boards/cats_rev1Pro/Core/Src/control/quaternion.c
> +/* ALL INPUTS AND OUTPUTS NEED TO BE 4,1 MATRIXES */
Matrices

2021-08-31 14:31 UTC, stojadin2701 reviewed
Minor comments

2021-08-31 17:00 UTC, stojadin2701 approved these changes

2021-09-01 11:50 UTC, l-jost requested changes

2021-09-02 12:35 UTC, l-jost approved these changes

2021-09-03 12:29 UTC, merged